<div class="alert alert-success">A Quick Start</div>

This notebook serves as a quick tutorial on using the solution evaluator provided. It aims to prevent syntax errors during usage. Before proceeding, ensure the environment is prepared and the necessary resources are downloaded. Refer to the [README](./README.md). for detailed instructions.

In [ ]:
# ignore this if you have installed DEAP
!pip install deap

Navigating to the repository directory, use the following command in the terminal or command prompt:
```sh
python evaluator.py <problem_type> <instance_name> <path_to_solution_file>
```
Replace <problem_type>, <instance_name>, and <path_to_solution_file> with appropriate values.
- `<problem_type> `must be one of the following: `cvrp` or `cvrptw`.
- `<instance_name>` is the name of the instance you want to evaluate.
- `<path_to_solution_file>` is the path to the solution file you want to evaluate against.

## Evaluating of a solution for a CVRP instance

In this example, we will be using the instance `X-n101-k25` from CVRP. 

The optimal solution for solving `X-n101-k25` are provided in `Solutions/cvrp` directory, i.e., `BKS-X-n101-k25.txt`.

Run the code cell below (or use the command in the terminal or command prompt).

In [1]:
!python evaluator.py cvrp X-n101-k25 Solutions/cvrp/BKS-X-n101-k25.txt

Problem:  cvrp  Instance name:  X-n101-k25  Solution path:  Solutions/cvrp/BKS-X-n101-k25.txt
File: /Users/weiyao/ML4VRP-GECCO2024/ML4VRP2024/Instances/cvrp/json/X-n101-k25.json exists.
Number of vehicles:  26 , Total distance:  27591.0 Objective value:  53591.0


The output should be (similar to) as shown below:
```sh
Problem:  cvrp  Instance name:  X-n101-k25  Solution path:  Solutions/cvrp/BKS-X-n101-k25.txt
File: .../Instances/cvrp/json/X-n101-k25.json exists.
Number of vehicles:  26 , Total distance:  27591 Objective value:  53591
```

## Evaluating of a solution for a CVRPTW instance

In this example, we will be using the instance `toy` from CVRPTW. 

Solutions for solving `toy` are provided in `Solutions/cvrptw` directory, including
- A feasible solution `toy_solution.txt` (in terms of the time window and vehicle capacity constraints) and
- An infeasible solution `toy_solution_infeasible.txt`.

Run the code cell below (or use the command in the terminal or command prompt).

In [2]:
!python evaluator.py cvrptw toy Solutions/cvrptw/toy_solution.txt

Problem:  cvrptw  Instance name:  toy  Solution path:  Solutions/cvrptw/toy_solution.txt
File: /Users/weiyao/ML4VRP-GECCO2024/ML4VRP2024/Instances/cvrptw/json/toy.json exists.
Number of vehicles:  2 , Total distance:  153.8 Objective value:  2153.8


The output is (similar to) as shown below:
```sh
Problem:  cvrptw  Instance name:  toy  Solution path:  Solutions/cvrptw/toy_solution.txt
File: .../Instances/cvrptw/json/toy.json exists.
Number of vehicles:  2 , Total distance:  153.82268590411263 Objective value:  2153.8226859041124
```

The infeasible solution cannot pass the feasibility check, thus no objective function value will be returned. 

In [3]:
!python evaluator.py cvrptw toy Solutions/cvrptw/toy_solution_infeasible.txt

Problem:  cvrptw  Instance name:  toy  Solution path:  Solutions/cvrptw/toy_solution_infeasible.txt
File: /Users/weiyao/ML4VRP-GECCO2024/ML4VRP2024/Instances/cvrptw/json/toy.json exists.
invalid capacity
invalid time window: too late to serve customer  6
The solution in infeasible!


The output is (similar to) as shown below:
```sh
Problem:  cvrptw  Instance name:  toy  Solution path:  Solutions/cvrptw/toy_solution_infeasible.txt
File: .../Instances/cvrptw/json/toy.json exists.
invalid capacity
invalid time window: too late to serve customer  6
The solution in infeasible!
```